Repository Cotecna-Inspection/Domain.Core, pull requests merged in 2021-11, with the labels that each got.

#11 Added a new HandlerAsync returning a T result
  Cotecna.Domain.Core.Test/TestCommands.cs
  Cotecna.Domain.Core/ApplicationMediator.cs
  Cotecna.Domain.Core/Cotecna.Domain.Core.csproj
  Cotecna.Domain.Core/IAsyncCommandHandler.cs
Labels: enhancement

#13 Fix async handler command t
  Cotecna.Domain.Core.Configuration/Cotecna.Domain.Core.Configuration.csproj
  Cotecna.Domain.Core.Configuration/ServiceCollectionExtensions.cs
  Cotecna.Domain.Core.Test/ApplicationMediatorTests.cs
  Cotecna.Domain.Core.Test/TestCommands.cs
  Cotecna.Domain.Core/ApplicationMediator.cs
  Cotecna.Domain.Core/Command.cs
  Cotecna.Domain.Core/Cotecna.Domain.Core.csproj
  Cotecna.Domain.Core/IAsyncCommandHandler.cs
Labels: bug, enhancement

#15 Syntax alignment and documentation update
  Cotecna.Domain.Core.Configuration/Cotecna.Domain.Core.Configuration.csproj
  Cotecna.Domain.Core.Configuration/ServiceCollectionExtensions.cs
  Cotecna.Domain.Core.Test/ApplicationMediatorTests.cs
  Cotecna.Domain.Core/ApplicationMediator.cs
  Cotecna.Domain.Core/Command.cs
  Cotecna.Domain.Core/Contract.cs
  Cotecna.Domain.Core/Cotecna.Domain.Core.csproj
  Cotecna.Domain.Core/IAsyncCommandHandler.cs
  README.md
Labels: documentation

#16 Npm task-based package
  .gitignore
  NuGet/Cotecna.Domain.Core.Configuration/Cotecna.Domain.Core.Configuration.csproj
  NuGet/Cotecna.Domain.Core.Configuration/ServiceCollectionExtensions.cs
  NuGet/Cotecna.Domain.Core.Test/ApplicationMediatorTests.cs
  NuGet/Cotecna.Domain.Core.Test/Cotecna.Domain.Core.Test.csproj
  NuGet/Cotecna.Domain.Core.Test/TestCommands.cs
  NuGet/Cotecna.Domain.Core.Test/TestQueries.cs
  NuGet/Cotecna.Domain.Core/ApplicationMediator.cs
  NuGet/Cotecna.Domain.Core/Command.cs
  NuGet/Cotecna.Domain.Core/Contract.cs
  NuGet/Cotecna.Domain.Core/ContractException.cs
  NuGet/Cotecna.Domain.Core/Cotecna.Domain.Core.csproj
  NuGet/Cotecna.Domain.Core/IAsyncCommandHandler.cs
  NuGet/Cotecna.Domain.Core/IAsyncQueryHandler.cs
  NuGet/Cotecna.Domain.Core/ICommandHandler.cs
  NuGet/Cotecna.Domain.Core/IQueryHandler.cs
  NuGet/Cotecna.Domain.Core/Query.cs
  NuGet/Domain.Core.sln
  README.md
  npm/.mocharc.json
  npm/.npmignore
  npm/.nyrc.json
  npm/package.json
  npm/register.js
  npm/src/command-handler.interface.ts
  npm/src/command.ts
  npm/src/index.ts
  npm/src/invoke-result.ts
  npm/src/query-handler.interface.ts
  npm/src/query.ts
  npm/tests/tsconfig.json
  npm/tsconfig.json
Labels: enhancement

#17 Release package preparation
  README.md
  npm/package.json
Labels: enhancement, invalid
